name: pointconvformer_wrapper
channels:
- pyg
- pytorch
- nvidia
- conda-forge
dependencies:
- python
- nvidia::cudatoolkit
- pytorch::pytorch=*=*cuda*
- pytorch::torchvision
- pyg::pyg
- pyg::pytorch-cluster
# - pip:
#   - torch_cluster






